In [278]:
import random
import numpy as np
print(np.__version__)

2.4.2


In [279]:
list1 = ["   ","|","   ","|","   ","\n",
         "---","|","---","|","---","\n",
         "   ","|","   ","|","   ","\n",
         "---","|","---","|","---","\n",
         "   ","|","   ","|","   ","\n"]
list2 = [" 1 ","|"," 2 ","|"," 3 ","\n",
         "---","|","---","|","---","\n",
         " 4 ","|"," 5 ","|"," 6 ","\n",
         "---","|","---","|","---","\n",
         " 7 ","|"," 8 ","|"," 9 ","\n"]
list3 = [0,2,4,12,14,16,24,26,28]

board = np.zeros((3,3), dtype=int)

x = " X "
o = " O "
blank = "   "
options = [0,2,4,12,14,16,24,26,28]
xSlots = []
oSlots = []
winConditions = [[0,2,4],[12,14,16],[24,26,28],
                 [0,12,24],[2,14,26],[4,16,28],
                 [0,14,28],[4,14,24]]
turn = 0
counter = 1

In [283]:
print(board)
board[1,1] = 2
print(board)

[[0 0 0]
 [2 0 0]
 [0 0 0]]
[[0 0 0]
 [2 2 0]
 [0 0 0]]


In [281]:
print("Input O if you want to play O, Input X if you want to play X")
while True:
    user = input("Enter your choice: ").lower()
    if user == "o" or user == "x":
        break
    else:
        print("Invalid Input")
print(f"You have chosen to play as ", {user})

Input O if you want to play O, Input X if you want to play X
You have chosen to play as  {'x'}


In [282]:
while counter < 10:
    if turn == 0:
        if user == 'x':
            display2 = "".join(list2)
            print(display2)
            selection = int(input("Input number for your selection: "))
            point = list3[selection - 1]
            list1[point] = x
            list2[point] = blank
            xSlots.append(point)
            options.remove(point)
            print("Putting X in slot ", {selection})
            turn = 1
        else:
            randomNum = random.choice(options)
            list1[randomNum] = x
            list2[randomNum] = blank
            xSlots.append(randomNum)
            options.remove(randomNum)
            print("Putting X in slot ", {randomNum})
            display1 = "".join(list1)
            print(display1)
            turn = 1
    else:
        if user == 'o':
            display2 = "".join(list2)
            print(display2)
            selection = int(input("Input number for your selection: "))
            point = list3[selection - 1]
            list1[point] = o
            list2[point] = blank
            oSlots.append(point)
            options.remove(point)
            print("Putting X in slot ", {selection})
            turn = 0
        else:
            randomNum = random.choice(options)
            list1[randomNum] = o
            list2[randomNum] = blank
            oSlots.append(randomNum)
            options.remove(randomNum)
            print("Putting O in slot ", {randomNum})
            display1 = "".join(list1)
            print(display1)
            turn = 0


    for i in range(8):
        if set(oSlots) == set(winConditions[i]) or set(xSlots) == set(winConditions[i]):
            if turn == 0:
                display1 = "".join(list1)
                print(display1)
                print("O Wins!")
            else:
                display1 = "".join(list1)
                print(display1)
                print("X Wins!")
            counter = 10
            break
        else:
            if counter == 9:
                display1 = "".join(list1)
                print(display1)
                print("Draw!")
                break

    counter += 1

 1 | 2 | 3 
---|---|---
 4 | 5 | 6 
---|---|---
 7 | 8 | 9 

Putting X in slot  {1}
Putting O in slot  {16}
 X |   |   
---|---|---
   |   | O 
---|---|---
   |   |   

   | 2 | 3 
---|---|---
 4 | 5 |   
---|---|---
 7 | 8 | 9 

Putting X in slot  {2}
Putting O in slot  {26}
 X | X |   
---|---|---
   |   | O 
---|---|---
   | O |   

   |   | 3 
---|---|---
 4 | 5 |   
---|---|---
 7 |   | 9 

Putting X in slot  {3}
 X | X | X 
---|---|---
   |   | O 
---|---|---
   | O |   

X Wins!
